[package]
name = "argus-proto"
description = "gRPC contract for the Argus agent protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
tonic.workspace = true
tonic-prost.workspace = true
prost.workspace = true

[build-dependencies]
tonic-prost-build.workspace = true
protox.workspace = true
